### ISSUE TITLE
Continuos Integration Tool

### ISSUE THREAD

**Issue by guilhermeddf** [omsdotnet/BookmakerBoard#22]
Does this project use any Continuous Integration Tool? If so, is it online? (TravisCI, CircleCI), or offline tool (Jenkins, Hudson).

**Comment by PavelKulbida** [comment]
yes, we use online CI - AppVeyor
https://ci.appveyor.com/project/omsdotnet/bookmakerboard

**Comment by PavelKulbida** [comment]
> Does this project use any Continuous Integration Tool? If so, is it online? (TravisCI, CircleCI), or offline tool (Jenkins, Hudson).

yes, we use online CI - AppVeyor
https://ci.appveyor.com/project/omsdotnet/bookmakerboard

**Comment by guilhermeddf** [comment]
Thank you!
